In [1]:
import talib as ta
import pandas as pd 
from datetime import datetime,timedelta
import time
import yfinance as yf
from get_histdata import GetHistData_yf

In [2]:
# Get ticker list

data=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]
tickers=data['Symbol'].to_list()
tickers=["{}.NS".format(tick) for tick in tickers]
tickers.append('^NSEI')
# tickers

In [3]:
df=GetHistData_yf(tickers,datetime.today()-timedelta(90))

Getting historical using yfinance
Fetching data from 2022-03-14 00:00:00 to 2022-06-12 00:00:00
--- 104.29603576660156 seconds ---

In [4]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Symbol
Date,,,,,,,,
2022-03-14,725.950012,733.500000,724.000000,730.549988,1905433,0.0,0,ADANIPORTS.NS
2022-03-15,733.000000,736.000000,716.250000,721.299988,4228582,0.0,0,ADANIPORTS.NS
2022-03-16,726.000000,729.500000,721.000000,723.799988,2693057,0.0,0,ADANIPORTS.NS
2022-03-17,730.500000,743.799988,729.549988,740.099976,4957379,0.0,0,ADANIPORTS.NS
2022-03-21,741.000000,750.450012,725.400024,735.150024,6662688,0.0,0,ADANIPORTS.NS
...,...,...,...,...,...,...,...,...
2022-06-06,16530.699219,16610.949219,16444.550781,16569.550781,233600,0.0,0,^NSEI
2022-06-07,16469.599609,16487.250000,16347.099609,16416.349609,233800,0.0,0,^NSEI
2022-06-08,16474.949219,16514.300781,16293.349609,16356.250000,243500,0.0,0,^NSEI
2022-06-09,16263.849609,16492.800781,16243.849609,16478.099609,205000,0.0,0,^NSEI
2022-06-10,16283.950195,16324.700195,16172.599609,16201.799805,189700,0.0,0,^NSEI

In [10]:
# using TA-lib
for sym in df['Symbol'].unique():
    df1=df[df['Symbol']==sym]
#     print(df1['Close'])
#     break
    num=ta.CDLENGULFING(df1['Open'], df1['High'], df1['Low'], df1['Close'])
    if not num[num !=0].empty:
        print(sym,num[num !=0])

ADANIPORTS.NS Date
2022-03-23   -100
2022-04-19   -100
2022-05-04   -100
dtype: int32
APOLLOHOSP.NS Date
2022-03-17   -100
2022-03-28   -100
2022-04-05   -100
2022-05-24   -100
2022-05-26    100
2022-06-08    100
dtype: int32
ASIANPAINT.NS Date
2022-03-23   -100
2022-04-05    100
2022-04-27    100
2022-05-24   -100
dtype: int32
AXISBANK.NS Date
2022-03-21   -100
2022-03-23   -100
2022-04-01    100
2022-04-07    100
2022-04-12    100
2022-05-04   -100
2022-06-03   -100
dtype: int32
BAJAJ-AUTO.NS Date
2022-03-22    100
2022-04-01    100
2022-04-18    100
2022-04-19   -100
2022-04-25    100
2022-04-28   -100
2022-06-06    100
dtype: int32
BAJFINANCE.NS Date
2022-03-21   -100
2022-04-01    100
2022-05-04   -100
dtype: int32
BAJAJFINSV.NS Date
2022-03-25   -100
2022-04-01    100
2022-04-29   -100
2022-06-01   -100
dtype: int32
BHARTIARTL.NS Date
2022-04-04    100
2022-04-06    100
2022-04-12   -100
2022-05-09    100
2022-05-24   -100
2022-05-27   -100
2022-06-01   -100
2022-06-03   -100
dtype: int32
BPCL.NS Date
2022-04-06    100
2022-05-17    100
dtype: int32
BRITANNIA.NS Date
2022-04-28    100
2022-05-05   -100
2022-06-01   -100
dtype: int32
CIPLA.NS Date
2022-03-25   -100
2022-04-08   -100
2022-04-13   -100
2022-04-19   -100
2022-04-21   -100
2022-05-11    100
2022-06-01   -100
2022-06-03   -100
dtype: int32
COALINDIA.NS Date
2022-03-29   -100
2022-04-11    100
2022-04-29   -100
2022-06-07    100
2022-06-09    100
dtype: int32
DIVISLAB.NS Date
2022-03-29    100
2022-04-13    100
2022-04-19   -100
2022-04-21    100
2022-05-23   -100
2022-06-01   -100
dtype: int32
DRREDDY.NS Date
2022-04-19   -100
2022-05-04   -100
2022-05-19    100
dtype: int32
EICHERMOT.NS Date
2022-03-21   -100
2022-04-07    100
2022-04-19   -100
2022-05-24   -100
2022-06-02   -100
2022-06-09    100
dtype: int32
GRASIM.NS Date
2022-03-24    100
2022-04-08    100
2022-05-04   -100
dtype: int32
HCLTECH.NS Date
2022-03-24    100
2022-03-30   -100
2022-04-08   -100
2022-04-13   -100
2022-04-29   -100
dtype: int32
HDFC.NS Date
2022-03-23   -100
2022-04-13   -100
2022-05-02    100
dtype: int32
HDFCBANK.NS Date
2022-03-22    100
2022-03-23   -100
2022-04-25    100
2022-05-24    100
2022-06-09    100
dtype: int32
HDFCLIFE.NS Date
2022-03-21   -100
2022-04-01    100
2022-04-08    100
2022-04-18    100
2022-04-19   -100
2022-06-03   -100
2022-06-09    100
dtype: int32
HEROMOTOCO.NS Date
2022-03-29   -100
2022-04-19   -100
2022-05-25   -100
2022-06-07    100
dtype: int32
HINDALCO.NS Date
2022-04-11   -100
2022-04-19   -100
2022-04-28   -100
2022-06-03   -100
dtype: int32
HINDUNILVR.NS Date
2022-03-21   -100
2022-04-11   -100
2022-04-19   -100
2022-05-04   -100
dtype: int32
ICICIBANK.NS Date
2022-03-21   -100
2022-03-25   -100
2022-04-05   -100
2022-04-20   -100
2022-05-04   -100
2022-05-31    100
dtype: int32
INDUSINDBK.NS Date
2022-03-28    100
2022-04-05   -100
2022-04-12    100
2022-04-19   -100
2022-05-02    100
2022-05-24   -100
2022-06-02    100
dtype: int32
INFY.NS Date
2022-03-17   -100
2022-03-22    100
2022-04-19   -100
2022-04-29   -100
2022-05-09    100
2022-05-24   -100
2022-06-06    100
dtype: int32
ITC.NS Date
2022-04-19   -100
2022-05-02    100
2022-05-16   -100
2022-06-08   -100
dtype: int32
JSWSTEEL.NS Date
2022-03-22    100
2022-04-12   -100
2022-04-19   -100
2022-05-02    100
2022-05-04   -100
2022-06-03   -100
2022-06-06    100
dtype: int32
KOTAKBANK.NS Date
2022-03-23   -100
2022-04-01    100
2022-06-09    100
dtype: int32
LT.NS Date
2022-03-21   -100
2022-03-25   -100
2022-04-01    100
2022-04-06    100
2022-05-04   -100
2022-05-24   -100
2022-06-09    100
dtype: int32
M&M.NS Date
2022-03-23   -100
dtype: int32
MARUTI.NS Date
2022-03-23   -100
2022-04-12    100
2022-04-29   -100
2022-05-09    100
2022-05-13   -100
2022-06-03   -100
dtype: int32
NESTLEIND.NS Date
2022-03-25   -100
2022-04-18    100
2022-05-02    100
2022-06-03   -100
dtype: int32
NTPC.NS Date
2022-03-22   -100
2022-04-08   -100
2022-04-29   -100
2022-05-27   -100
dtype: int32
ONGC.NS Date
2022-03-31    100
2022-06-02    100
dtype: int32
POWERGRID.NS Date
2022-04-12    100
2022-04-19   -100
2022-05-17    100
2022-05-25   -100
2022-05-27   -100
dtype: int32
RELIANCE.NS Date
2022-04-08    100
2022-04-29   -100
2022-05-04   -100
2022-06-09    100
dtype: int32
SBIN.NS Date
2022-03-21   -100
2022-04-01    100
2022-04-29   -100
2022-05-18   -100
2022-06-03   -100
dtype: int32
SBILIFE.NS Date
2022-03-21   -100
2022-03-23   -100
2022-04-18    100
2022-04-19   -100
2022-04-28    100
2022-05-17    100
dtype: int32
SHREECEM.NS Date
2022-03-21   -100
2022-04-01    100
2022-05-11   -100
2022-05-24   -100
dtype: int32
SUNPHARMA.NS Date
2022-03-23   -100
2022-04-04    100
2022-04-08   -100
2022-05-24   -100
2022-05-30   -100
dtype: int32
TATAMOTORS.NS Date
2022-03-21   -100
2022-04-07   -100
2022-04-19   -100
2022-05-25   -100
dtype: int32
TATASTEEL.NS Date
2022-04-07   -100
2022-04-19   -100
2022-04-27    100
2022-06-03   -100
dtype: int32
TCS.NS Date
2022-04-13   -100
2022-05-17    100
2022-06-02    100
dtype: int32
TATACONSUM.NS Date
2022-03-23   -100
2022-04-12   -100
2022-04-19   -100
2022-05-23   -100
2022-06-03   -100
dtype: int32
TECHM.NS Date
2022-03-24    100
2022-04-08   -100
2022-05-13   -100
2022-05-18   -100
2022-05-24   -100
2022-06-01   -100
2022-06-08   -100
2022-06-09    100
dtype: int32
TITAN.NS Date
2022-04-01   -100
2022-04-13   -100
2022-04-18    100
dtype: int32
ULTRACEMCO.NS Date
2022-03-24    100
2022-06-03   -100
dtype: int32
UPL.NS Date
2022-05-25   -100
2022-06-03   -100
2022-06-09    100
dtype: int32
WIPRO.NS Date
2022-03-25   -100
2022-04-01    100
2022-04-05   -100
2022-05-24   -100
2022-06-01   -100
2022-06-09    100
dtype: int32
^NSEI Date
2022-03-21   -100
2022-03-31   -100
2022-04-01    100
2022-04-29   -100
2022-05-04   -100
2022-06-01   -100
2022-06-02    100
2022-06-09    100
dtype: int32