In [1]:
import pandas as pd
import yfinance as yf
from get_histdata import GetHistData_yf
from getTickers import nifty200tickers,nifty50tickers
from datetime import datetime,timedelta
import warnings
warnings.simplefilter(action='ignore', category=Warning)

In [2]:
tickers=["{}.NS".format(tick) for tick in nifty50tickers()]

In [3]:
df= GetHistData_yf(tickers,datetime.today()-timedelta(365))
df['Close']=df['Adj Close']
df.drop(columns='Adj Close',inplace=True)

Getting historical using yfinance
Fetching data from 2021-06-24 00:00:00 to None
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
--- 18.004145622253418 seconds ---

In [4]:
df

,Open,High,Low,Close,Volume,Symbol
Date,,,,,,
2021-06-24,724.000000,725.000000,701.700012,709.900024,21503302,ADANIPORTS.NS
2021-06-25,715.000000,719.000000,706.500000,712.200012,12085421,ADANIPORTS.NS
2021-06-28,719.000000,729.950012,713.000000,716.250000,14139292,ADANIPORTS.NS
2021-06-29,717.500000,723.000000,709.000000,711.000000,9303151,ADANIPORTS.NS
2021-06-30,717.599976,717.599976,702.099976,703.700012,9100756,ADANIPORTS.NS
...,...,...,...,...,...,...
2022-06-20,409.000000,417.899994,404.149994,414.649994,10375419,WIPRO.NS
2022-06-21,420.000000,426.750000,416.649994,425.149994,6093902,WIPRO.NS
2022-06-22,422.700012,422.700012,410.299988,411.250000,8101431,WIPRO.NS
2022-06-23,412.500000,420.799988,411.299988,419.049988,9827505,WIPRO.NS
2022-06-24,421.000000,426.000000,415.750000,418.049988,5999210,WIPRO.NS

In [5]:
pct_check=5
multiplier=((100-pct_check)/100)
for tick in df.Symbol.unique():
    
    df1=df[df['Symbol']==tick]
    
    close=round(df1.iloc[-1]['Close'],2)
    high52=round(df1['Close'].max(),2)
    
    if close >= high52*multiplier:
        diff=close - df1['Close'].max()
        pct_chg=round(abs(diff)/high52*100,2)
        if diff = 0 :
            print("{} is trading at {} ; it's 52W High - {}".format(tick,close,pct_chg,high52))
        elif diff < 0:
            print("{} is trading at {} : {} % below it's 52W High - {}".format(tick,close,pct_chg,high52))
        else:
            print("{} is trading at it's 52W High - {}".format(tick,pct_chg,high52))

EICHERMOT.NS is trading at 2856.45 : 2.54 % below it's 52W High - 2931.0
HEROMOTOCO.NS is trading at 2739.9 : 4.53 % below it's 52W High - 2869.84
ITC.NS is trading at 265.55 : 3.37 % below it's 52W High - 274.8
M&M.NS is trading at 1062.35 : 0.0 % above it's 52W High - 1062.35